name: CMake Matrix CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Debug, Release]
        compiler: [msvc, gcc]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            compiler: gcc
      fail-fast: false

    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ ninja-build

    - name: Install CMake (Windows)
      if: runner.os == 'Windows'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes --force

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DENCHANTUM_BUILD_TESTS=ON
        ${{ matrix.os == 'windows-latest' && '-G "Visual Studio 17 2022" -A x64' || '-G Ninja' }}

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Run Tests
      run: ctest --test-dir build -C ${{ env.BUILD_TYPE }} --output-on-failure
